version : '3.9'

services:
  #MongoDB services
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  #Node API service
  api: 
    build: .
    ports: 
      - "3001:3001"
    depends_on:
      - mongo